# Generated by Django 3.2.23 on 2024-02-14 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='profiles/default_profile.png', null=True, upload_to='profiles/')),
                ('profile_bio', models.TextField()),
                ('fav_brand', models.CharField(blank=True, choices=[('acer', 'Acer'), ('apple', 'Apple'), ('asus', 'Asus'), ('dell', 'Dell'), ('google', 'Google'), ('hp', 'HP'), ('msi', 'MSI'), ('toshiba', 'Toshiba'), ('sony', 'Sony')], default='', max_length=30, null=True)),
                ('fav_operating_system', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS')], default='', max_length=30, null=True)),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('default_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('default_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_county', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
