# Generated by Django 3.2.23 on 2024-02-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
