# Generated by Django 3.2.23 on 2024-02-15 00:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fav_brand',
            field=models.CharField(blank=True, choices=[('acer', 'Acer'), ('apple', 'Apple'), ('asus', 'Asus'), ('dell', 'Dell'), ('google', 'Google'), ('hp', 'HP'), ('msi', 'MSI'), ('toshiba', 'Toshiba'), ('sony', 'Sony')], default='', max_length=30, null=True, verbose_name='Favourite Brand'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fav_operating_system',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS')], default='', max_length=30, null=True, verbose_name='Favourite Operating System'),
        ),
    ]
