# Generated by Django 3.2.23 on 2024-02-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='fav_operating_system',
            new_name='fav_os',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_street_address2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Street                                               Address 2'),
        ),
    ]
