# Generated by Django 3.2.23 on 2024-03-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'User Contacts'},
        ),
    ]
