# Generated by Django 3.2.23 on 2024-03-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='emailaddress',
        ),
    ]
