# Generated by Django 3.2.23 on 2024-03-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
