# Generated by Django 3.2.23 on 2024-01-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='about/no_product_image.webp', null=True, upload_to='about/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street_address_1', models.CharField(blank=True, max_length=200, null=True)),
                ('street_address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city_or_town', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
