# Generated by Django 3.2.23 on 2024-01-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='company_name',
            new_name='name',
        ),
    ]
