# Generated by Django 3.2.23 on 2024-01-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_company_name_about_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Company'},
        ),
    ]
