# Generated by Django 3.2.23 on 2024-01-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='opening_hours_bank_holidays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='opening_hours_mon_friday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='opening_hours_sat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='opening_hours_sunday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
