# Generated by Django 3.2.23 on 2024-01-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20240130_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='opening_hours_mon_friday',
            new_name='opening_hours_mon_to_fri',
        ),
    ]
