# Generated by Django 3.2.23 on 2024-02-16 17:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20240204_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
