# Generated by Django 3.2.23 on 2024-02-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_about_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, default='default_images/no_image.webp', null=True, upload_to='about/'),
        ),
    ]
