# Generated by Django 3.2.23 on 2024-01-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='battery_life',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='memory_ram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('acer', 'Acer'), ('apple', 'Apple'), ('asus', 'Asus'), ('dell', 'Dell'), ('google', 'Google'), ('hp', 'HP'), ('msi', 'MSI'), ('toshiba', 'Toshiba'), ('sony', 'Sony')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS')], default='', max_length=30, null=True),
        ),
    ]
