# Generated by Django 3.2.23 on 2024-03-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240306_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('acer', 'Acer'), ('apple', 'Apple'), ('asus', 'Asus'), ('dell', 'Dell'), ('google', 'Google'), ('hp', 'HP'), ('msi', 'MSI'), ('toshiba', 'Toshiba'), ('sony', 'Sony'), ('samsung', 'Samsung'), ('hisense', 'Hisense'), ('windows', 'Windows')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS'), ('chromeos', 'ChromeOS')], default='', max_length=30, null=True),
        ),
    ]
