# Generated by Django 3.2.23 on 2024-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240307_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('acer', 'Acer'), ('apple', 'Apple'), ('asus', 'Asus'), ('beats', 'Beats'), ('dell', 'Dell'), ('google', 'Google'), ('hisense', 'Hisense'), ('hp', 'HP'), ('lg', 'LG'), ('marshall', 'Marshall'), ('msi', 'MSI'), ('panasonic', 'Panasonic'), ('samsung', 'Samsung'), ('sennheiser', 'Sennheiser'), ('sharp', 'Sharp'), ('sony', 'Sony'), ('toshiba', 'Toshiba'), ('windows', 'Windows'), ('xiaomi', 'Xiaomi')], default='', max_length=30, null=True),
        ),
    ]
